package com.mycompany.miparqueoumg;
import java.util.HashMap;
import java.io.*;
import java.util.*;
import java.util.List;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author barri
 */
public class CargaArchivos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CargaArchivos.class.getName());

    private static void setModel(DefaultTableModel modelo) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * Creates new form CargaArchivos
     */
    public CargaArchivos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        areas = new javax.swing.JTable();
        leer = new javax.swing.JButton();
        cargar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        spots = new javax.swing.JTable();
        leer2 = new javax.swing.JButton();
        cargar2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        vehiculos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        leer3 = new javax.swing.JButton();
        cargar3 = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(255, 255, 255));
        setName("Archivos"); // NOI18N

        areas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "area-id", "nombre", "capacidad", "tipo-vehiculo"
            }
        ));
        jScrollPane1.setViewportView(areas);

        leer.setText("Leer");
        leer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 255, 255), new java.awt.Color(0, 204, 204), new java.awt.Color(204, 0, 0), new java.awt.Color(153, 255, 255)));
        leer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerActionPerformed(evt);
            }
        });

        cargar.setText("Cargar");
        cargar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 204, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(204, 0, 0), new java.awt.Color(153, 255, 255)));
        cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("AREAS");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("SPOTS");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        spots.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "spot-id", "area-id", "tipo-vehiculo", "status"
            }
        ));
        jScrollPane2.setViewportView(spots);

        leer2.setText("Leer");
        leer2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 255, 255), new java.awt.Color(51, 255, 204), new java.awt.Color(204, 0, 51), new java.awt.Color(0, 153, 153)));
        leer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leer2ActionPerformed(evt);
            }
        });

        cargar2.setText("Cargar");
        cargar2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 255, 255), new java.awt.Color(51, 255, 204), new java.awt.Color(204, 0, 0), new java.awt.Color(102, 255, 255)));
        cargar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargar2ActionPerformed(evt);
            }
        });

        vehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "placa", "tipo-vehiculo", "tipo-area"
            }
        ));
        jScrollPane3.setViewportView(vehiculos);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("VEHICULOS");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        leer3.setText("Leer");
        leer3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 255, 255), new java.awt.Color(0, 255, 204), new java.awt.Color(153, 51, 0), new java.awt.Color(0, 153, 153)));
        leer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leer3ActionPerformed(evt);
            }
        });

        cargar3.setText("Cargar");
        cargar3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 255, 255), new java.awt.Color(0, 255, 204), new java.awt.Color(153, 0, 0), new java.awt.Color(0, 153, 153)));
        cargar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargar3ActionPerformed(evt);
            }
        });

        Regresar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Regresar.setText("Regresar");
        Regresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(153, 153, 0), new java.awt.Color(51, 204, 0), new java.awt.Color(0, 0, 153), new java.awt.Color(0, 153, 153)));
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(leer, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cargar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(leer2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cargar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(leer3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cargar3, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(leer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cargar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(leer2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cargar2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(leer3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cargar3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(Regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 @SuppressWarnings("unchecked")
    private void leerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerActionPerformed
JFileChooser fileChooser = new JFileChooser();
fileChooser.setDialogTitle("Selecciona un archivo de áreas");
// Mostrar el diálogo y capturar el resultado
int resultado = fileChooser.showOpenDialog(this);
if (resultado == JFileChooser.APPROVE_OPTION) {
// Obtener el archivo seleccionado
File archivoSeleccionado = fileChooser.getSelectedFile();
String ruta = archivoSeleccionado.getAbsolutePath();
// Lista donde guardaremos los datos leídos
List<String[]> datos = new ArrayList<>();
// Leer archivo
    try (BufferedReader br = new BufferedReader(new FileReader(ruta))) {
        String linea;
        while ((linea = br.readLine()) != null) {
            if (linea.trim().isEmpty()) continue;
            // Usa "\\|" si tu separador es un pipe
            String[] partes = linea.split(","); 
            if (partes.length == 4) {
                datos.add(new String[]{
                    partes[0].trim(),
                    partes[1].trim(),
                    partes[2].trim(),
                    partes[3].trim()
                });
            }
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this,
                "Error al leer el archivo:\n" + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    // Mostrar en la tabla
    DefaultTableModel modelo = (DefaultTableModel) areas.getModel();
    modelo.setRowCount(0); // Limpiar tabla
    for (String[] fila : datos) {
        modelo.addRow(fila);
    }
    JOptionPane.showMessageDialog(this, "Se cargaron " + datos.size() + " áreas.");
}
    }//GEN-LAST:event_leerActionPerformed

    private void leer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leer2ActionPerformed
JFileChooser fileChooser = new JFileChooser();
fileChooser.setDialogTitle("Selecciona un archivo de spot");
// Mostrar el diálogo y capturar el resultado
int resultado = fileChooser.showOpenDialog(this);
if (resultado == JFileChooser.APPROVE_OPTION) {
// Obtener el archivo seleccionado
File archivoSeleccionado = fileChooser.getSelectedFile();
String ruta = archivoSeleccionado.getAbsolutePath();
// Lista donde guardaremos los datos leídos
List<String[]> datos = new ArrayList<>();
// Leer archivo
    try (BufferedReader br = new BufferedReader(new FileReader(ruta))) {
        String linea;
        while ((linea = br.readLine()) != null) {
            if (linea.trim().isEmpty()) continue;
            // Usa "\\|" si tu separador es un pipe
            String[] partes = linea.split(","); 
            if (partes.length == 4) {
                datos.add(new String[]{
                    partes[0].trim(),
                    partes[1].trim(),
                    partes[2].trim(),
                    partes[3].trim()
                });
            }
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this,
                "Error al leer el archivo:\n" + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    // Mostrar en la tabla
    DefaultTableModel modelo;
    modelo = (DefaultTableModel) spots.getModel();
    modelo.setRowCount(0); // Limpiar tabla
    for (String[] fila : datos) {
        modelo.addRow(fila);
    }
    JOptionPane.showMessageDialog(this, "Se cargaron " + datos.size() + " spot.");
}             
    }//GEN-LAST:event_leer2ActionPerformed

    private void leer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leer3ActionPerformed
JFileChooser fileChooser = new JFileChooser();
fileChooser.setDialogTitle("Selecciona un archivo de vehiculos");
// Mostrar el diálogo y capturar el resultado
int resultado = fileChooser.showOpenDialog(this);
if (resultado == JFileChooser.APPROVE_OPTION) {
// Obtener el archivo seleccionado
File archivoSeleccionado = fileChooser.getSelectedFile();
String ruta = archivoSeleccionado.getAbsolutePath();
// Lista donde guardaremos los datos leídos
List<String[]> datos = new ArrayList<>();
// Leer archivo
    try (BufferedReader br = new BufferedReader(new FileReader(ruta))) {
        String linea;
        while ((linea = br.readLine()) != null) {
            if (linea.trim().isEmpty()) continue;
            // Usa "\\|" si tu separador es un pipe
            String[] partes = linea.split(","); 
            if (partes.length == 3) {
                datos.add(new String[]{
                    partes[0].trim(),
                    partes[1].trim(),
                    partes[2].trim()
                });
            }
        }
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this,
                "Error al leer el archivo:\n" + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    // Mostrar en la tabla
    DefaultTableModel modelo;
    modelo = (DefaultTableModel) vehiculos.getModel();
    modelo.setRowCount(0); // Limpiar tabla
    for (String[] fila : datos) {
        modelo.addRow(fila);
    }
    JOptionPane.showMessageDialog(this, "Se cargaron " + datos.size() + " vehiculos.");
}             
    }//GEN-LAST:event_leer3ActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
     Parqueo Parqueo = new Parqueo ();
     Parqueo.setVisible (true);
     this.dispose();
    }//GEN-LAST:event_RegresarActionPerformed

    private void cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarActionPerformed
DefaultTableModel modelo = (DefaultTableModel) areas.getModel();
int totalFilas = modelo.getRowCount();
if (totalFilas == 0) {
JOptionPane.showMessageDialog(this, 
"La tabla está vacía. No hay nada que cargar.", 
"Error", 
JOptionPane.ERROR_MESSAGE);
return;
}
// 2. Variables de Conexión (Arregla 'cannot find symbol: url', etc.)
// ⚠️ ¡DEBES CAMBIAR LA CONTRASEÑA!
String url = "jdbc:mysql://localhost:3306/miparqueoumg";
String usuario = "root"; // O tu usuario de MySQL
String contrasena = ""; // ⬅️ PON TU CONTRASEÑA AQUÍ
String sql = "INSERT INTO `areas` (`area-id`, `nombre`, `capacidad`, `tipo-vehiculo`) VALUES (?, ?, ?, ?)";
Connection con = null;
PreparedStatement ps = null;
try {
    // 4. Conectar
    con = DriverManager.getConnection(url, usuario, contrasena);
    con.setAutoCommit(false); // Para ejecutar como lote  
    // 5. Preparar la consulta
    ps = con.prepareStatement(sql);
    // 6. Recorrer la JTable
    for (int i = 0; i < totalFilas; i++) {       
        // Obtener datos de la JTable
        String idStr = modelo.getValueAt(i, 0).toString();
        String nombre = modelo.getValueAt(i, 1).toString();
        String capacidadStr = modelo.getValueAt(i, 2).toString();
        String tipoVehiculo = modelo.getValueAt(i, 3).toString();
        // 7. Convertir datos (Arregla 'NumberFormatException')
        int capacidad = Integer.parseInt(capacidadStr); // Solo convertimos capacidad
        // 8. Asignar valores a la consulta (?)
        ps.setString(1, idStr); // ⬅️ CORREGIDO: Usamos setString para "A01"
        ps.setString(2, nombre);
        ps.setInt(3, capacidad);
        ps.setString(4, tipoVehiculo);       
        ps.addBatch(); // Añadir al lote
    }
    // 10. Ejecutar todo el lote
    int[] resultados = ps.executeBatch();   
    // 11. Confirmar la transacción
    con.commit(); 
    JOptionPane.showMessageDialog(this, 
            "Se cargaron exitosamente " + resultados.length + " registros.", 
            "Carga Exitosa", 
            JOptionPane.INFORMATION_MESSAGE);
} catch (NumberFormatException e) {
    // Error si "capacidad" no es un número
    JOptionPane.showMessageDialog(this, 
            "Error en los datos de la tabla.\n'capacidad' debe ser un número.\n" + e.getMessage(), 
            "Error de Formato", 
            JOptionPane.ERROR_MESSAGE); 
} catch (SQLException e) {
    // Error de Base de Datos (conexión, consulta, etc.)
    JOptionPane.showMessageDialog(this, 
            "Error al guardar en la base de datos:\n" + e.getMessage(), 
            "Error de SQL", 
            JOptionPane.ERROR_MESSAGE);
    // Si algo falló, revertir la transacción
    try {
        if (con != null) con.rollback();
    } catch (SQLException ex) {
        // Muestra error en consola   
    }     
} finally {
    // 12. Cerrar la conexión (MUY IMPORTANTE)
    try {
        if (ps != null) ps.close();
        if (con != null) {
            con.setAutoCommit(true); 
            con.close();
        }
    } catch (SQLException e) {
        // Muestra error en consola
    }
}
    }//GEN-LAST:event_cargarActionPerformed

    private void cargar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargar2ActionPerformed
DefaultTableModel modelo = (DefaultTableModel) spots.getModel();
int totalFilas = modelo.getRowCount();
if (totalFilas == 0) {
JOptionPane.showMessageDialog(this, 
"La tabla está vacía. No hay nada que cargar.", 
"Error", 
JOptionPane.ERROR_MESSAGE);
return;
}
String url = "jdbc:mysql://localhost:3306/miparqueoumg";
String usuario = "root"; 
String contrasena = ""; 
String sql = "INSERT INTO `spot` (`spot-id`, `area-id`, `tipo-vehiculo`, `status`) VALUES (?, ?, ?, ?)";
Connection con = null;
PreparedStatement ps = null;
try {
con = DriverManager.getConnection(url, usuario, contrasena);
con.setAutoCommit(false);
ps = con.prepareStatement(sql);
for (int i = 0; i < totalFilas; i++) {
        String spotid = modelo.getValueAt(i, 0).toString();
        String areaid = modelo.getValueAt(i, 1).toString();
        String tipovehiculo = modelo.getValueAt(i, 2).toString();
        String status = modelo.getValueAt(i, 3).toString();
        ps.setString(1, spotid); 
        ps.setString(2, areaid);
        ps.setString(3, tipovehiculo);
        ps.setString(4, status);       
        ps.addBatch(); 
    }
    int[] resultados = ps.executeBatch();
    con.commit(); 
    JOptionPane.showMessageDialog(this, 
            "Se cargaron exitosamente " + resultados.length + " registros.", 
            "Carga Exitosa", 
            JOptionPane.INFORMATION_MESSAGE);
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, 
            "Error en los datos de la tabla.\n'capacidad' debe ser un número.\n" + e.getMessage(), 
            "Error de Formato", 
            JOptionPane.ERROR_MESSAGE);          
} catch (SQLException e) {
    JOptionPane.showMessageDialog(this, 
            "Error al guardar en la base de datos:\n" + e.getMessage(), 
            "Error de SQL", 
            JOptionPane.ERROR_MESSAGE);
    try {
        if (con != null) con.rollback();
    } catch (SQLException ex) {  
    }         
} finally {
    try {
        if (ps != null) ps.close();
        if (con != null) {
            con.setAutoCommit(true); 
            con.close();
        }
    } catch (SQLException e) {       
    }
}
    }//GEN-LAST:event_cargar2ActionPerformed

    private void cargar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargar3ActionPerformed
DefaultTableModel modelo = (DefaultTableModel) vehiculos.getModel();
int totalFilas = modelo.getRowCount();
if (totalFilas == 0) {
JOptionPane.showMessageDialog(this, 
"La tabla está vacía. No hay nada que cargar.", 
"Error", 
JOptionPane.ERROR_MESSAGE);
return;
}
String url = "jdbc:mysql://localhost:3306/miparqueoumg";
String usuario = "root";
String contrasena = "";
String sql = "INSERT INTO `vehiculos` (`placa`, `tipo-vehiculo`, `tipo-area`) VALUES (?, ?, ?)";
Connection con = null;
PreparedStatement ps = null;
try {
    con = DriverManager.getConnection(url, usuario, contrasena);
    con.setAutoCommit(false);
    ps = con.prepareStatement(sql);
    for (int i = 0; i < totalFilas; i++) {        
        String placa = modelo.getValueAt(i, 0).toString();
        String tipovehiculo = modelo.getValueAt(i, 1).toString();
        String tipoarea = modelo.getValueAt(i, 2).toString();
        ps.setString(1, placa); 
        ps.setString(2, tipovehiculo);
        ps.setString(3, tipoarea);
        ps.addBatch();
    }
    int[] resultados = ps.executeBatch();
    con.commit(); 
    JOptionPane.showMessageDialog(this, 
            "Se cargaron exitosamente " + resultados.length + " registros.", 
            "Carga Exitosa", 
            JOptionPane.INFORMATION_MESSAGE);
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, 
            "Error en los datos de la tabla.\n'capacidad' debe ser un número.\n" + e.getMessage(), 
            "Error de Formato", 
            JOptionPane.ERROR_MESSAGE);            
} catch (SQLException e) {
    JOptionPane.showMessageDialog(this, 
            "Error al guardar en la base de datos:\n" + e.getMessage(), 
            "Error de SQL", 
            JOptionPane.ERROR_MESSAGE);
    try {
        if (con != null) con.rollback();
    } catch (SQLException ex) {    
    }       
} finally {
    try {
        if (ps != null) ps.close();
        if (con != null) {
            con.setAutoCommit(true); 
            con.close();
        }
    } catch (SQLException e) {    
    }
}
    }//GEN-LAST:event_cargar3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CargaArchivos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Regresar;
    private javax.swing.JTable areas;
    private javax.swing.JButton cargar;
    private javax.swing.JButton cargar2;
    private javax.swing.JButton cargar3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton leer;
    private javax.swing.JButton leer2;
    private javax.swing.JButton leer3;
    private javax.swing.JTable spots;
    private javax.swing.JTable vehiculos;
    // End of variables declaration//GEN-END:variables
}
